name: Build and Publish NuGet Package

on:
  push:
    tags:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      
      - name: Setup .NET Core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '8.x' # Adjust based on your project's requirements

      - name: Get latest tag
        id: tag
        run: echo "::set-output name=tag::$(git describe --abbrev=0 --tags)"

      - name: Build and Pack
        run: dotnet pack -c Release -o ./output --version-suffix=${{ steps.tag.outputs.tag }} -p:PackageID=TGHarker.Temporalio.Actors

      - name: Publish NuGet package
        run: dotnet nuget push ./output/*.nupkg --source "https://www.nuget.org/api/v2/package" --api-key ${{ secrets.NUGET_API_KEY }}
